### ISSUE TITLE
additional options for the graphs

### ISSUE THREAD

**Issue by molly78** [yoctopuce/YoctoCloud#2]
Not an issue per se, but is there any chance of adding in 3 sets of Plot Bands for the Y axis?

http://www.highcharts.com/docs/chart-concepts/plot-bands-and-plot-lines

This seems to be beyond my limited skill set, but perhaps after seeing one change like this I can do additional changes on my own, ie adding in the option of showing the data labels for example.

Also any chance of supporting the export module? Perhaps selfishly for Chromium on the Pi?

http://www.highcharts.com/docs/export-module/export-module-overview

Once again much thanks for this most excellent example code, it's gotten me 90% to my objective - a smart monitor for my smoker / sous vide cooker / long-duration cooking in general.

**Comment by yoctopuce** [comment]
Well, we'll see what we can do. No promise though.

**Comment by molly78** [comment]
I hated even asking, just given one example of adding in extra options to the graph means I may be able to add in others on my own. 

Huge thanks, and no worries if not :)

**Comment by yoctopuce** [comment]
Done and done.  The horizontal plot bands are available for the 1rst Y axis only. We hope this limitation sounds reasonable enough for you.

**Comment by molly78** [comment]
Wow?!? You guys simply rock - seriously!

Most appreciated for the horizontal bands, to set the temperature ranges for smoking meats, sous vide and other cooking projects I have going on so I don't have to keep remembering.

Man, this rocks!

One edit I've done is to change the default date ranges to something more applicable for my situation:

Around line 1983, I changed

```
        rangeSelector: {
            buttons: [{ count:1, type:'hour', text: ' hour ' }, 
                      { count:1, type:'day', text: ' day ' }, 
                      { count:7, type:'day', text: ' week ' }, 
                      { count:1, type:'month', text: ' month ' }, 
                      { type:'all', text: 'All' }],
            selected: 2,
             <?php printObjectInitCode(RANGESEL_OBJ);?>
         },

```

to


```
        rangeSelector: {
            buttons: [{ count:24, type:'hour', text: ' 24hr ' }, 
                      { count:12, type:'hour', text: ' 12hr ' }, 
                      { count:3, type:'hour', text: ' 3hr ' }, 
                      { count:30, type:'minute', text: ' 30m ' }, 
                      { count:5, type:'minute', text: ' 5m ' }, 
                      { type:'all', text: 'All' }],
            selected: 4,
             <?php printObjectInitCode(RANGESEL_OBJ);?>
         },
```

Man, so stoked & cant wait for my PT100 & my sensors from http://www.auberins.com/ to arrive now & get cooking.

Huge thanks for your awesome support again!

**Comment by yoctopuce** [comment]
You're welcome. Closing the issue then.

**Comment by molly78** [comment]
To add data labels edit line ~1973
lots of plotOptions can be set here
```


    plotOptions:{series: {
      marker: {
            enabled: true,
            radius: 3,
            fillColor: '#FFFFFF',
            lineWidth: 1,
            lineColor: null // inherit from series

      },
      
      dataLabels:{
            enabled:true,
        // round to one decimal place
            format: '{point.y:,.1f}',
            allowOverlap:false,
            y: -20,
            style: {fontSize: '12px'},
            rotation: 315
     },
     
     connectNulls: false,
//     pointPlacement: 'on',
     
/*
    Solid
    ShortDash
    ShortDot
    ShortDashDot
    ShortDashDotDot
    Dot
    Dash
    LongDash
    DashDot
    LongDashDot
    LongDashDotDot
*/     
     dashStyle: 'LongDashDotDot',
     enableMouseTracking: false,
     animation: false}
     
     },
    
```

**Comment by molly78** [comment]
~ line 2662
set both to 

`viewport.setAttribute('content', 'user-scalable=no, device-width');`


```
 function updateOrientation()  // thanks stackoverflow 
  {  var viewport = document.querySelector("meta[name=viewport]");
	 if (typeof window.orientation !== 'undefined') 
	 { switch (window.orientation)
	   { case 90:
	     case -90:
            viewport.setAttribute('content', 'user-scalable=no, device-width');
			break;
         default:		  
	    viewport.setAttribute('content', 'user-scalable=no, device-width');
	   }
	 }	 


```



from the absolute numbers in the code - works much much better on my iPhone / iPad's screens
